### PR TITLE
define the missing properties to avoid notices and close div to avoid layout error

### PR DESCRIPTION
**Pull request by johnnypraxis**
define the missing properties "profile_field_year" and "profile_field_programmename" to avoid notices;
close div element to avoid layout error on overview.php

### CODE REVIEW

**Comment by jgramp** [comment]
Hi Delvon - was this change implemented?

**Comment by delvon** [comment]
Hi Jess - Those were done from just after the pilot I believe. AM certain we do have those errors now.

**Comment by aspark21** [comment]
profile_field_programmename is in, so done -> https://github.com/uclmoodle/moodle-report_myfeedback/blob/master/student/overview.php#L19-L23

the missing div does not appear to be here -> https://github.com/uclmoodle/moodle-report_myfeedback/blob/master/student/overview.php#L112
@johnnypraxis could you clarify what this resolves with screenshots please

profile_field_year -> The expected profile field is now courseyear not year, has not been added -> https://github.com/uclmoodle/moodle-report_myfeedback/blob/master/index.php#L233

Will need to rebase on master

**Comment by aspark21** [comment]
no reply so will close, big code maintenance effort just completed so will need to a fresh look wether still relevant

**Pull request closed without merging**
